### ISSUE TITLE
The line-up has been updated

### ISSUE THREAD

**Issue by andersklenke** [mikker/rf15-schedule#1]
Hey! 

Great work with this api! 

The Roskilde line-up has been updated. Would you mind, update your schedule.md file? I can do it, but I thought you maybe have some kind of automatic script?

**Comment by mikker** [comment]
Sadly I don't. Made it from scratch. So if you can you should definitely do it!

**Comment by mikker** [comment]
Looks like you're on it – great! If the scripts give you trouble I can run them if not then :+1: :boom:

**Comment by mikker** [comment]
Fixed by #2
